context:
  version: "11.0.1"

package:
  name: cyclonedds-py
  version: ${{ version }}

source:
  - url: https://github.com/eclipse-cyclonedds/cyclonedds-python/archive/refs/tags/${{ version }}.zip
    sha256: 3e809253fa926e8a23a33d6fd696873c43d6c99a5894cc8634ae0696c505ba97
    patches:
      - 0000_assert.patch

build:
  number: 1
  python:
    entry_points:
      - ddsls = cyclonedds.tools.ddsls:command
      - ddsls = cyclonedds.tools.pubsub:command
      - cyclonedds = cyclonedds.tools.cli.main:cli


requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
  host:
    - cyclonedds ==${{ version }}
    - python
    - pip
    - setuptools
    - rich-click
  run:
    - python
    - cyclonedds ==${{ version }}
    - rich-click



tests:
  - script:
      - cyclonedds --help
  - python:
      imports:
        - cyclonedds
      pip_check: true


about:
  homepage: https://cyclonedds.io/docs/
  documentation: https://cyclonedds.io/docs/cyclonedds-python/latest/
  repository: https://github.com/eclipse-cyclonedds/cyclonedds-python
  summary: Python binding for Eclipse Cyclone DDS
  license: EPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nmarticorena
